In [1]:
import matplotlib.pyplot as plt
from datetime import timedelta
import pandas as pd

### Reading data

In [2]:
df = pd.read_csv("../Data/raw/taxi_trips.csv")

In [3]:
df.head(5)

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,...,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude
0,1,2016-03-01 00:00:00,2016-03-01 00:07:55,1,2.50,1,N,NaN,NaN,1,...,0.5,2.05,0.00,0.3,12.35,NaN,-73.976746,40.765152,-74.004265,40.746128
1,1,2016-03-01 00:00:00,2016-03-01 00:11:06,1,2.90,1,N,NaN,NaN,1,...,0.5,3.05,0.00,0.3,15.35,NaN,-73.983480,40.767925,-74.005940,40.733166
2,2,2016-03-01 00:00:00,2016-03-01 00:31:06,2,19.98,1,N,NaN,NaN,1,...,0.5,8.00,0.00,0.3,63.80,NaN,-73.782020,40.644810,-73.974540,40.675770
3,2,2016-03-01 00:00:00,2016-03-01 00:00:00,3,10.78,1,N,NaN,NaN,1,...,0.5,3.78,5.54,0.3,41.62,NaN,-73.863420,40.769814,-73.969650,40.757767
4,2,2016-03-01 00:00:00,2016-03-01 00:00:00,5,30.43,3,N,NaN,NaN,1,...,0.0,0.00,15.50,0.3,113.80,NaN,-73.971740,40.792183,-74.177170,40.695053

#### Data overview

In [4]:
# Null count
df.isnull().sum()

vendorid                        0
tpep_pickup_datetime            0
tpep_dropoff_datetime           0
passenger_count                 0
trip_distance                   0
ratecodeid                      0
store_and_fwd_flag              0
pulocationid             12210952
dolocationid             12210952
payment_type                    0
fare_amount                     0
extra                           0
mta_tax                         0
tip_amount                      0
tolls_amount                    0
improvement_surcharge           0
total_amount                    0
congestion_surcharge     12210952
pickup_longitude                0
pickup_latitude                 0
dropoff_longitude               0
dropoff_latitude                0
dtype: int64

In [18]:
# Columns datatypes
df.dtypes

vendorid                          int64
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                   int64
trip_distance                   float64
ratecodeid                        int64
store_and_fwd_flag               object
pulocationid                    float64
dolocationid                    float64
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
pickup_longitude                float64
pickup_latitude                 float64
dropoff_longitude               float64
dropoff_latitude                float64
payment_label                    object
trip_duration_min               float64
dtype: object

In [16]:
# General statistics
df.describe()

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,pulocationid,dolocationid,payment_type,fare_amount,...,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration_min
count,1.219840e+07,12198402,12198402,1.219840e+07,1.219840e+07,1.219840e+07,12198402.0,12198402.0,1.219840e+07,1.219840e+07,...,1.219840e+07,1.219840e+07,1.219840e+07,1.219840e+07,12198402.0,1.219840e+07,1.219840e+07,1.219840e+07,1.219840e+07,1.219840e+07
mean,1.531154e+00,2016-03-16 09:20:20.992821504,2016-03-16 09:36:10.351603968,1.659995e+00,6.137767e+00,1.038749e+00,0.0,0.0,1.340275e+00,1.279549e+01,...,1.794240e+00,3.151049e-01,2.997357e-01,1.604777e+01,0.0,-7.287561e+01,4.014585e+01,-7.300812e+01,4.021979e+01,1.582265e+01
min,1.000000e+00,2016-03-01 00:00:00,2016-03-01 00:01:40,0.000000e+00,0.000000e+00,1.000000e+00,0.0,0.0,1.000000e+00,-3.760000e+02,...,-2.000000e+01,-1.604000e+01,-3.000000e-01,-3.763000e+02,0.0,-1.616987e+02,0.000000e+00,-1.616987e+02,0.000000e+00,1.666667e-02
25%,1.000000e+00,2016-03-08 17:31:04,2016-03-08 17:47:20.249999872,1.000000e+00,1.000000e+00,1.000000e+00,0.0,0.0,1.000000e+00,6.500000e+00,...,0.000000e+00,0.000000e+00,3.000000e-01,8.750000e+00,0.0,-7.399174e+01,4.073632e+01,-7.399126e+01,4.073471e+01,6.550000e+00
50%,2.000000e+00,2016-03-16 10:37:09.500000,2016-03-16 10:55:17,1.000000e+00,1.700000e+00,1.000000e+00,0.0,0.0,1.000000e+00,9.500000e+00,...,1.350000e+00,0.000000e+00,3.000000e-01,1.180000e+01,0.0,-7.398161e+01,4.075325e+01,-7.397963e+01,4.075378e+01,1.090000e+01
75%,2.000000e+00,2016-03-24 00:25:35,2016-03-24 00:41:29,2.000000e+00,3.180000e+00,1.000000e+00,0.0,0.0,2.000000e+00,1.450000e+01,...,2.360000e+00,0.000000e+00,3.000000e-01,1.776000e+01,0.0,-7.396678e+01,4.076765e+01,-7.396236e+01,4.076912e+01,1.760000e+01
max,2.000000e+00,2016-03-31 23:59:59,2016-06-29 15:58:16,9.000000e+00,1.907263e+07,9.900000e+01,0.0,0.0,4.000000e+00,4.294967e+05,...,8.500000e+02,1.410320e+03,3.000000e-01,4.295622e+05,0.0,0.000000e+00,6.685682e+01,0.000000e+00,5.079786e+01,1.458679e+05
std,4.990285e-01,NaN,NaN,1.312614e+00,6.159649e+03,4.469367e-01,0.0,0.0,4.900591e-01,1.341651e+02,...,2.549393e+00,1.744611e+00,1.211061e-02,1.344248e+02,0.0,8.946978e+00,4.928559e+00,8.396655e+00,4.625489e+00,9.963351e+01

### Data Preparation

In [7]:
# Transforming datetime objects
df['tpep_dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])
df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])

In [8]:
# Labeling payment methods
payment_map = {
    1: "Credit Card",
    2: "Cash",
    3: "No Charge",
    4: "Dispute"
}

df["payment_label"] = df["payment_type"].map(payment_map)

In [9]:
# Trip duration im minutes transformation
df["trip_duration_min"] = (
    df["tpep_dropoff_datetime"] - df["tpep_pickup_datetime"]
).dt.total_seconds() / 60

In [17]:
# Cleaning data
df = df[df["trip_duration_min"] > 0] # Removing trips with no duration time
df = df.fillna(0) # Fill NaN values to "0"

#### Data Graphics

In [11]:
# Trip distance distribution
df_distance = df[df["trip_distance"] < 25]
plt.hist(df_distance["trip_distance"], bins=25)
plt.title("Trip Distance Distribution ")
plt.xlabel("Distance (miles)")
plt.ylabel("Frequency")
plt.savefig("../Data/Silver/graph1_distance.png")
plt.clf()

In [12]:
# Payment method distribution
counts = df["payment_label"].value_counts()
counts.plot(kind="bar")
plt.title("Payment Method Distribution")
plt.xlabel("Payment Type")
plt.ylabel("Number of Trips")
plt.xticks(rotation=30)
plt.tight_layout()
plt.savefig("../Data/Silver/graph2_payment_type.png")
plt.clf()

In [13]:
# Daily revenue over time
df.groupby(df["tpep_pickup_datetime"].dt.to_period("D"))["total_amount"].sum().plot()
plt.title("Daily Revenue Over Time")
plt.xlabel("Date")
plt.ylabel("Total Revenue (dollar)")
plt.xticks(rotation=45)
plt.tight_layout() 
plt.savefig("../Data/Silver/graph3_revenue.png")
plt.clf()

In [14]:
# Passenger count distribution
df_clean = df[(df["passenger_count"] > 0) & (df["passenger_count"] <= 6)]
counts = df_clean["passenger_count"].value_counts().sort_index()
counts.plot(kind="bar")
plt.title("Passenger Count Distribution")
plt.xlabel("Number of Passengers")
plt.ylabel("Number of Trips")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig("../Data/Silver/graph4_passenger_count.png")
plt.clf()

In [ ]:
# Trip duration distribution
df_clean = df[
    (df["trip_duration_min"] > 0) & 
    (df["trip_duration_min"] < 300)  
]
plt.hist(df_clean["trip_duration_min"], bins=50)
plt.title("Trip Duration Distribution")
plt.xlabel("Duration (minutes)")
plt.ylabel("Frequency")
plt.tight_layout()
plt.savefig("../Data/Silver/graph5_duration.png")
plt.clf()